### ISSUE TITLE
Serial1.begin question

### ISSUE THREAD

**Issue by branonbarrett** [dfowler7437/SparkCorePolledTimer#1]
What exactly is the Serial1.begin(115200); line doing? I found a [nice thread here](http://arduino.stackexchange.com/questions/1569/what-is-serial-begin9600) that explains what serial.begin does, but I can't fugure out what it's buying in your example. Can you please help a noob out?

**Comment by dfowler7437** [comment]
Branon,

I should have removed that from the example.. Serial1 opens the second serial port which I use for debugging in my environment. I don’t like trying to use the USB to serial port cause it comes as goes as you develop and that causes problems with the PC.  I connect a second serial port to the core, and use Serial1 instead of the normal Serial.  

David.

---

David Fowler https://plus.google.com/u/0/+DavidFowlerEngineer/about

**Comment by branonbarrett** [comment]
Thanks David!
